In [10]:
import sys
sys.path.append("../")
sys.path.append("../multimodal/examples")

In [11]:
import datasets
import transformers

from flava.data import TorchVisionDataModule, TextDataModule
from flava.data.datamodules import MMDataModule
from flava.definitions import FLAVAArguments
from flava.utils import build_config, build_datamodule_kwargs
from flava.model import FLAVAClassificationLightningModule
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [12]:
from hydra.utils import instantiate
from omegaconf import OmegaConf
#conf_yaml = OmegaConf.load("../multimodal/examples/flava/configs/finetuning/qnli.yaml")
conf_yaml = OmegaConf.load("../configs/finetuning/mm_sst2_test.yaml")
config = instantiate(conf_yaml)
datamodule = MMDataModule(
            **build_datamodule_kwargs(config.datasets.vl, config.training))

In [13]:
datamodule.setup("fit")

Using custom data configuration israfelsr--multimodal_sst-196b843417c02b29
Reusing dataset parquet (/Users/israfelsalazar/.cache/huggingface/datasets/parquet/israfelsr--multimodal_sst-196b843417c02b29/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901)
Using custom data configuration israfelsr--multimodal_sst-196b843417c02b29
Reusing dataset parquet (/Users/israfelsalazar/.cache/huggingface/datasets/parquet/israfelsr--multimodal_sst-196b843417c02b29/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901)


  0%|          | 0/21 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

  0%|          | 0/21 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

In [14]:
# colored images
for sample in datamodule.train_dataset:
    print(sample.keys())
    print(sample['text'])
    print(sample['input_ids'])
    break

dict_keys(['text', 'label', 'image', 'input_ids', 'token_type_ids', 'special_tokens_mask', 'attention_mask'])
hide new secretions from the parental units 
tensor([  101,  5342,  2047,  3595,  8496,  2013,  1996, 18643,  3197,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,  

In [8]:
# black images
for sample in datamodule.train_dataset:
    print(sample.keys())
    print(sample['image'])
    display(sample['image'])
    break

dict_keys(['text', 'label', 'image', 'input_ids', 'token_type_ids', 'special_tokens_mask', 'attention_mask'])
tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

      

tensor([[[-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         ...,
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179],
         [-2.1179, -2.1179, -2.1179,  ..., -2.1179, -2.1179, -2.1179]],

        [[-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         ...,
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357],
         [-2.0357, -2.0357, -2.0357,  ..., -2.0357, -2.0357, -2.0357]],

        [[-1.8044, -1.8044, -1.8044,  ..., -1.8044, -1.8044, -1.8044],
         [-1.8044, -1.8044, -1.8044,  ..., -1

In [27]:
text = []
image = []
for t, batch in enumerate(datamodule.train_dataloader()):
    datamodule.on_before_batch_transfer(batch)
    datamodule.transfer_batch_to_device(batch, 'cpu', t)
    datamodule.on_after_batch_transfer(batch)
    image.append(batch.get("image", None))
    text.append(batch.get("text", None))
    if t==2:
        break

In [30]:
text[0].shape

torch.Size([16, 512])